name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn job
      - run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: panel-docs.tuyacn.com

      - name: Update CDN
        run: |
          curl https://purge.jsdelivr.net/gh/TuyaInc/tuya-panel-kit-docs@gh-pages/shields.json
          curl https://cdn.jsdelivr.net/gh/TuyaInc/tuya-panel-kit-docs@gh-pages/types-assets.json
