name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main # default branch
  schedule:
    - cron: 0 0 * * 0
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn job
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: panel-docs.tuyacn.com
          keep_files: true

      - name: Update CDN
        run: |
          curl https://purge.jsdelivr.net/gh/tuya/tuya-panel-kit-docs@gh-pages/shields.json
          curl https://purge.jsdelivr.net/gh/tuya/tuya-panel-kit-docs@gh-pages/types-assets.json
